name: Auto Update Blog

on:
  schedule:
    - cron: '0 8,14 * * *'  # 8 AM and 2 PM UTC
  workflow_dispatch:

jobs:
  update-blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Bot
      run: python bot.py

    - name: Commit & Push JSON
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add blogdata.json
        git commit -m "Auto-update blog posts"
        git push
      continue-on-error: true
